# Generated by Django 3.0.7 on 2020-06-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Заголовок', max_length=50)),
                ('topic', models.CharField(default='Тема', max_length=50)),
                ('icon', models.CharField(default='http://demidob.site/dch/imgs/none.jpg', max_length=150)),
                ('body', models.TextField(default='Текст блога')),
            ],
        ),
    ]
