# Generated by Django 3.0.7 on 2020-06-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
