# Generated by Django 3.0.7 on 2020-06-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.CharField(default='0', max_length=25, primary_key=True, serialize=False),
        ),
    ]
