# Generated by Django 3.0.7 on 2020-06-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200606_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='icon',
            field=models.CharField(default='http://demidob.site/dch/imgs/none.jpg', max_length=150),
        ),
    ]
