# Generated by Django 3.0.7 on 2020-06-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='producer',
            field=models.CharField(default='Неизвестный', max_length=50),
        ),
    ]
