# Generated by Django 3.0.7 on 2020-06-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.TextField(default='', primary_key=True, serialize=False)),
                ('json', models.TextField(default='{}')),
            ],
        ),
    ]
