# Generated by Django 3.0.7 on 2020-06-27 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('article', models.CharField(default='0', max_length=25, primary_key=True, serialize=False)),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
    ]
